# Numpy Arrays

In [2]:
import numpy as np

**Converting a 1-D list to NP array**

In [3]:
# Initializing a python list and checking its type
my_list = [1,2,3]
type(my_list)

list

In [4]:
# Converting it to np array and then checking its type
np_array = np.array(my_list)
type(np_array)

numpy.ndarray

**Converting a 2-D list to NP array**

In [5]:
# Initializing a 2-D python list and printing it
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [6]:
# We converted that list to a np array, and numpy already had idea that this is a matrix
# i.e. a 2-D list, so it printed it out in 2-D form
print(np.array(my_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Making NP array with built-in functions**

In [7]:
# Remember, it uses one "r".
arr = np.arange(0, 10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
# Doing it with a step-size of 2
print(np.arange(0,10,2))

[0 2 4 6 8]


In [9]:
# Getting array of 0s
# By default, np returns floating point numbers

np.zeros(5)

# See how we got an array of 5 zeros.

array([0., 0., 0., 0., 0.])

In [10]:
# Now lets create an array of 5x5

np.zeros((5,5))

# Remember, we need to pass it with double paranthesis for 2x2.

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
# Coming towards linspace now. It returns numbers between a range.
# Forexample, I want 5 numbers in between 0 to 10. The code is as follow

np.linspace(0,10,5)

# Remember, it does include the upper bound of the range. It gives evenly spaced numbers

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
# Now let's make an identity matrix with the eye function

np.eye(3)

# The reason we pass a single number is because an ID matrix is always nxn.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# Generating some random number arrays. Remember, its not a random number generator.
# Its a generator of random number arrays

np.random.rand(2,3)

# The random numbers fall in between the range of 0-1. And they are returned from a
# uniform distribution

array([[0.77217532, 0.40370646, 0.50547233],
       [0.82817637, 0.57414763, 0.68862934]])

In [14]:
#  Reutrning numbers from random distribution
np.random.randn(1,3)

array([[-0.59358231, -2.37998712, -0.36459547]])

In [15]:
# Getting random integers
np.random.randint(0, 10)

3

In [16]:
# We can get arrays of random integers
np.random.randint(0, 10, (2,3))

array([[8, 4, 0],
       [0, 0, 5]])

In [17]:
# Reshaping numbers
arr1 = np.arange(0, 24)

arr1.reshape(4,6)

# Reshaping cannot be done to something like 5x4, remember, y*n should return the number
# elements contained in that array.

arr1.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [18]:
# Max and min functions
arr2 = np.random.randint(0, 10, 10)
print(arr2)

print(arr2.max())

print(arr2.argmax())

# Similar for min and argmin

[1 3 0 9 1 7 7 4 2 3]
9
3


# Numpy Indexing and Slicing

In [23]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
# Grabbing single element

print(arr[8])

# Grabbing a slice
print(arr[1:5])

# Grabbing a slice given default start to some end
print(arr[:6])

# Grabbing a slice given a start to the end of the array
print(arr[5:])

8
[1 2 3 4]
[0 1 2 3 4 5]
[5 6 7 8 9]


**Numpy Broadcasting**

In [30]:
# Broadcasting is changing multiple values in an array to one same value
arr[0:5] = 100
print(arr)

[100 100 100 100 100   5   6   7   8   9]


In [33]:
# Resetting the array
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [41]:
# Broadcasting a complete slice of array
slice_of_arr = arr[0:5]

slice_of_arr[:] = 99
print(slice_of_arr)

print(arr)

# The slice of the array acts as a pointer to the original array, thus the values
# are changed in the original array too

[99 99 99 99 99]
[99 99 99 99 99  5  6  7  8  9]


**Indexing in 2D arrays**

In [56]:
arr_2d = [[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]]
np.array(arr_2d)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [62]:
# Grabbing a row
print(arr_2d[1])

# Grabbing an element
print(arr_2d[1][2])

[6, 7, 8, 9, 10]
8


In [65]:
# Checking if all the elements of arr are greater than 4.
arr > 4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

# Numpy Operations

In [72]:
arr = np.arange(0,10)
print(arr)

# addition
print("addition: ", arr + 5)

# subtraction
print("addition: ", arr - 5)

# The same for multiplication and division
# We can add, subtract, multiply, and divide array with arrays too. Remember, we need
# to have same shapes of array to do so

# Array addition
print(arr+arr)

# Array division
print(arr/arr)

[0 1 2 3 4 5 6 7 8 9]
addition:  [ 5  6  7  8  9 10 11 12 13 14]
addition:  [-5 -4 -3 -2 -1  0  1  2  3  4]
[ 0  2  4  6  8 10 12 14 16 18]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


/tmp/ipykernel_32/3412227932.py:18: RuntimeWarning: invalid value encountered in divide
  print(arr/arr)


In [77]:
# Some advanced function

print("Square Root: ", np.sqrt(arr))

print("Sin: ", np.sin(arr))

print("Log: ", np.log(arr))

Square Root:  [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
Sin:  [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
Log:  [      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


/tmp/ipykernel_32/1031039474.py:7: RuntimeWarning: divide by zero encountered in log
  print("Log: ", np.log(arr))


In [82]:
# Some other functions
print("Sum of the array: ", arr.sum())
print("Mean of the array:", arr.mean())
print("Variance of the array: ", arr.var())
print("Standard Deviation of the array: ", arr.std())

Sum of the array:  45
Mean of the array: 4.5
Variance of the array:  8.25
Standard Deviation of the array:  2.8722813232690143


**Performing Operations on 2D arrays**

In [85]:
arr_2d = np.arange(0, 25).reshape(5,5)
print(arr_2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [87]:
print(arr_2d.sum())

300


In [89]:
# Sum of the columns
print(arr_2d.sum(axis=0))

# Sum of the rows
print(arr_2d.sum(axis=1))

[50 55 60 65 70]
[ 10  35  60  85 110]


# Excercises

**Create an array of 10 zeros**

In [90]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Create an array of 10 ones**

In [91]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Create an array of 10 fives**

In [94]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

**Create an array of random integeres ranging from 10-50**

In [96]:
np.random.randint(10,50, (1,10))

array([[22, 11, 23, 44, 35, 33, 47, 25, 18, 12]])

**Create a 3x3 matrix with values ranging from 0-8**

In [99]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Create a 3x3 identity matrix**

In [100]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Use Numpy to generate a random number between 0 and 1**

In [102]:
np.random.rand()

0.15285753411445713

**Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution**

In [103]:
np.random.randn(1,25)

array([[-0.75405451,  0.93813103, -0.10418984, -0.95096784,  1.04715134,
         0.47431915, -0.36876009, -1.66701922,  0.46240609, -0.87442518,
         0.18301742, -0.14543219,  0.5120429 , -0.35055532,  0.66232787,
        -0.03942422, -1.80472398,  1.44844234, -0.35682812,  1.05706669,
         1.39819403,  0.48917065,  1.08146206, -1.12939363,  1.15865052]])

# The End